### PR TITLE
More efficient QgsFeature selection

### PR DESCRIPTION
**Pull request by ymoisan**
This PR is really a discussion type PR.  

In relation to GISeHealth#26, where tests suggest layer.selectedFeatures() may be a little heavy memorywise, this PR is about constructing a list of QgsFeature objects as small as possible.  In the current version, we get full features (with all attributes and geometry) through the call to selectedFeatures().  I don't know how much memory a QgsFeature object takes, but the current behaviour is bound to bite us when the number of features selected is large, especially when features have many attributes.

What we are proposing here (and asking your advice on) is to filter feature objects so as to only get the PK field and no other attribute (and no geometry).  We're not quite satisfied with our proposed implementation because : 

- we need to use versioning_base.pg_pk to find out what the referring table's PK field is
- we still have a list of QgsFeature objects

In an ideal world, we would instead use selectedFeaturesIds() because it just returns a list of ids that could then be passed on to versioning_base.checkout.  This approach is an order of magnitude faster than making up a list of feature objects (verified empirically).  Unfortunately, the keyColumn() function of a QgsDataSourceURI does NOT return the PK of the table versioned through the view object the QgsDataSourceURI points to.  If we could make it such that keyColumn() returns the actual PK of the related versioned table, we would gain a lot in terms of performance.

Suggestions welcome.

P.S. I also sneaked in a way to get rid of full paths for sqlite files.  That's my (and  our users') preference of course but I noticed in case of very long paths some menu icons get kicked out of sight.  You can still get them by clicking on the >> symbol, but that's not handy.  Same applies for a PG object (when database + schema + name = long) as shown in GISeHealth#1 but we're not proposing anything for that yet.  Some fixed width object would be preferable, but we don't know what yet.

### CODE REVIEW

**Comment by ymoisan** [comment]
Test show that : 
- layer.selectedFeaturesIds() works; too bad QgsDataSourceURI.keyColumn() is unreliable to get the actual PK field name ...)
- all sorts of fiddling with QgsFeature objects fails : 

1) The basic : 
```Python
layer_selected_features = layer.selectedFeatures()
```
2) Filtering feature objects to get rid of everything except the table_pk : 
```Python
layer_selected_features_ids = layer.selectedFeaturesIds()
user_selected_features.append(list(layer.getFeatures(QgsFeatureRequest()
.setFilterFids(layer_selected_features_ids)
. setFlags( QgsFeatureRequest.NoGeometry )
.setSubsetOfAttributes( [table_pk],layer.pendingFields() ))))
```
3) using an optimized selectedFeaturesIterator object : 
```Python
layerSelectedFeaturesIterator = layer.selectedFeaturesIterator()
layer_selected_features_ids = list(i[table_pk] for i in layerSelectedFeaturesIterator)
user_selected_features.append(layer_selected_features_ids)
```
Whenever a list of QgsFeature objects is involved, there comes a time when the number of selected features is large enough that the list doesn't get filled.  It remains empty.  No error is reported and the code just continues as if there had been no error.

**Comment by vmora** [comment]
@ymoisan apparently guessing 'pseudo'' pk on a view complicated (qgis master gives up an proposes to select from a list).

Normally the intial table pk should be ok (found through postgis db inspection) so you could store it in versionnig metadata table and retrievs set the correct pk in qgis.

**Comment by ymoisan** [comment]
@vmora : the problem for me is not to get the PK.  The problem is I want to use layer.selectedFeaturesIds() and for that I think I need QgsDataSourceURI.keyColumn() to return the right column name.  I know I can change the keyColum, but that does not work once the layer is loaded : 

lyr1 = iface.activeLayer()
uri = QgsDataSourceURI(lyr1.source())
uri.keyColumn()
  u'objectid'
lyr1selectedFeaturesIds = lyr1.selectedFeaturesIds()
lyr1selectedFeaturesIds
  [325L, 5341L, 38L, 433L, 5604L, 116L, 372L, 17152L] # objectid values
uri.setKeyColumn('id')
uri.keyColumn()
  u'id'
lyr1selectedFeaturesIds = lyr1.selectedFeaturesIds()
lyr1selectedFeaturesIds
 [325L, 5341L, 38L, 433L, 5604L, 116L, 372L, 17152L] # Still objectid values

I hoped I could do a simple "if PK != keyColumn()" then setKeyColumn(PK) and then use selectedFeaturesIds but I can't.  I can't find a way to avoid building lists of QgsFeature objects.

**Comment by vmora** [comment]
@ymoisan that's normal, the QgsDataSourceURI(lyr1.source()) returns a copy, not a reference. I'm not sure you can change the uri of the layer once loaded (look at the c++ api doc to check)

The simplest and most reliable way to set the key column is to do it before loading the layer (do what you do to uri, and pass it to the layer constructor).

**Comment by ymoisan** [comment]
@vmora: thanx; that's what's shown [here](http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/loadlayer.html).

**Comment by ymoisan** [comment]
@vmora: one thing I notice is that the "id" field we use as PK in the original table is nullable in the trunk_rev_head view : 

| #  | Name| Type  |Length | Null| Default                                 |
|:--:|:---:|:-----:|:-----:|:---:|:---------------------------------------:|
| 1  | id  | int4  |4      | **Y**  |  |

But not in the original table, as per definition of a primary key : 

| #  | Name| Type  |Length | Null| Default                                 |
|:--:|:---:|:-----:|:-----:|:---:|:---------------------------------------:|
| 1  | id  | int4  |4      | **N**   | nextval('schema.table_id_seq'::regclass)|

The article here is quite interesting : http://stackoverflow.com/questions/17301323/why-are-my-views-columns-nullable.  If we found a way for views to have a clear non nullable int4 field then I guess we'd stand a better chance at getting the right field name in keyColumn().

**Comment by ymoisan** [comment]
I found something simpler.  Will do another PR tomorrow.

**Comment by ymoisan** [comment]
I decided to leave the responsibility of having the right PK once the view is loaded to the user.  This can easily be done by simply editing the .qgs file and replacing the (wrong) key value in <datasource> objects of type PG.

What I do in the plugin is just check if QGIS guessed the versioned table (view) PK right by comparing it to the actual table PK.  If not, I throw a pop up saying checkout will proceed without the feature selection the user did.

The reason is that all forms of QGSFeature objects lists -- selectedFeatures(), selectedFeaturesIterator(), optimized with filters or not -- fail at some point when the feature selection is too large.  I force the use of selectedFeaturesIds() which is incredibly scalable (and relies on the PK value being the right one).

Code fix : 3c426a5

@vmora : are you OK with that ?  I'll let you know when you can merge.

Thanx

**Comment by vmora** [comment]
Looking good to me.

**Comment by ymoisan** [comment]
@vmora : got the "go" from my testers, so ready for PR.  Test pass; rebased  at 1d98350 (Note : I squashed the recent commits instead of the old ones).  Once the PR is included I'll update my other dev branches and continue work.  Other PRs to come shortly.  Thanx.

**Pull request merged**
