### PR TITLE
Documentation v1

### PR DESCRIPTION
**Pull request by ymoisan**
I have integrated all the comments that I received so I think we are ready for a PR.  Already rebased.

Thanx.

### CODE REVIEW

**Comment by vmora** [comment]
+1 for merge, can you rebase/squash before that ?

**Comment by ymoisan** [comment]
I had already squashed 6 commits down to 2. I made it to one now.  

Question : do you mind having more than one commit for bigger PRs ?  I figure some PRs need a little more history sometimes.

Thanx.

**Comment by vmora** [comment]
The number of commits can be big, it's just that "Almost version 1" is not really an interesting commit msg :)

**Comment by ymoisan** [comment]
indeed :-)

**Comment by ymoisan** [comment]
@vmora : could you proceed with the PR ?  Busy with the QGIS 2.14 release ? ;-)

**Pull request merged**
